### ISSUE TITLE
"OpenCV Manager package was not found!"

### ISSUE THREAD

**Issue by zampnrs** [RobertYCXu/opticalflow-opencv-android#1]
Hi there!

First, congratulations for you project on github! 

I'm trying to use it on my android device, I've added the OpenCVLibrary341 to the project in android studio, than it has been successfully built. When I launch the app in my device, I recieve this error: "OpenCV Manager package was not found! Try to install it?". 

Should I do anything more than add the OpenCVLibrary341 to the project?

Thanks in advance...

**Comment by serviceberry3** [comment]
If anyone still needs the solution, it's here: https://answers.opencv.org/question/60991/opencv-library-package-was-not-found-try-to-install-it-button-yesno/

**Comment by u-eng** [comment]
Facing same error. It shouldn't show that message when we have copied libs from OpenCV-sdk into our project folder, isn't it? Dunno why it is showing!

**Comment by u-eng** [comment]
Gets resolved only after manually installing through adb as mentioned in above link, even if you copied libs.
